name: mlhc_project
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - duckdb
  - gensim
  - nltk
  - numpy<2
  - pandas=2.3.*
  - scikit-learn=1.7.*
  - scipy<1.13
  - xgboost=3.0.5
  - pyarrow=21.0.0
  - matplotlib
